name: my_finance1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  cloud_firestore: ^5.6.5
  get: ^4.7.2
  sqflite: ^2.4.2
  path: ^1.9.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  pie_chart: ^5.4.0
  shared_preferences: ^2.5.2
  intl: ^0.20.2
  flutter_slidable: ^4.0.0
  material_floating_search_bar_2: ^0.5.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  flutter_staggered_animations: ^1.1.1
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/